version: "2"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: blog_db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=blog
      - MARIADB_DATABASE=blog
    volumes:
      - "./mariadb_persistence:/bitnami/mariadb"

  larablog:
    image: docker.io/bitnami/laravel:8
    container_name: larablog
    ports:
      - "6500:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=blog
      - DB_DATABASE=blog
    volumes:
      - "./larablog:/app"
      - "./posts_html:/app/public/posts_html"
    depends_on:
      - mariadb

  nextblog:
    build: ./nextblog/
    image: ikodi/nextblog
    container_name: nextblog
    ports:
      - "6600:3000"
    environment:
      - PORT=3000
    depends_on:
      - mariadb
