version: "2"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: blog_db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=blog
      - MARIADB_DATABASE=blog
  larablog:
    image: docker.io/bitnami/laravel:8
    container_name: larablog
    ports:
      - "6500:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=blog
      - DB_DATABASE=blog
    volumes:
      - "./app:/app"
    depends_on:
      - mariadb
